// Metro bundler ne peut pas résoudre les require() dynamiques : carte statique obligatoire.
const cardImages: Record<string, number> = {
  '01': require('../assets/images/card_01.png'),
  '02': require('../assets/images/card_02.png'),
  '03': require('../assets/images/card_03.png'),
  '04': require('../assets/images/card_04.png'),
  '05': require('../assets/images/card_05.png'),
  '06': require('../assets/images/card_06.png'),
  '07': require('../assets/images/card_07.png'),
  '08': require('../assets/images/card_08.png'),
  '09': require('../assets/images/card_09.png'),
  '10': require('../assets/images/card_10.png'),
  '11': require('../assets/images/card_11.png'),
  '12': require('../assets/images/card_12.png'),
  '13': require('../assets/images/card_13.png'),
  '14': require('../assets/images/card_14.png'),
  '15': require('../assets/images/card_15.png'),
  '16': require('../assets/images/card_16.png'),
  '17': require('../assets/images/card_17.png'),
  '18': require('../assets/images/card_18.png'),
  '19': require('../assets/images/card_19.png'),
  '20': require('../assets/images/card_20.png'),
  '21': require('../assets/images/card_21.png'),
  '22': require('../assets/images/card_22.png'),
  '23': require('../assets/images/card_23.png'),
  '24': require('../assets/images/card_24.png'),
  '25': require('../assets/images/card_25.png'),
  '26': require('../assets/images/card_26.png'),
  '27': require('../assets/images/card_27.png'),
  '28': require('../assets/images/card_28.png'),
  '29': require('../assets/images/card_29.png'),
  '30': require('../assets/images/card_30.png'),
  '31': require('../assets/images/card_31.png'),
  '32': require('../assets/images/card_32.png'),
  '33': require('../assets/images/card_33.png'),
  '34': require('../assets/images/card_34.png'),
  '35': require('../assets/images/card_35.png'),
  '36': require('../assets/images/card_36.png'),
  '37': require('../assets/images/card_37.png'),
  '38': require('../assets/images/card_38.png'),
  '39': require('../assets/images/card_39.png'),
  '40': require('../assets/images/card_40.png'),
};

export default cardImages;
