// Metro bundler ne peut pas résoudre les require() dynamiques : carte statique obligatoire.
const cardImages: Record<string, number> = {
  '01': require('../assets/images/card_01.webp'),
  '02': require('../assets/images/card_02.webp'),
  '03': require('../assets/images/card_03.webp'),
  '04': require('../assets/images/card_04.webp'),
  '05': require('../assets/images/card_05.webp'),
  '06': require('../assets/images/card_06.webp'),
  '07': require('../assets/images/card_07.webp'),
  '08': require('../assets/images/card_08.webp'),
  '09': require('../assets/images/card_09.webp'),
  '10': require('../assets/images/card_10.webp'),
  '11': require('../assets/images/card_11.webp'),
  '12': require('../assets/images/card_12.webp'),
  '13': require('../assets/images/card_13.webp'),
  '14': require('../assets/images/card_14.webp'),
  '15': require('../assets/images/card_15.webp'),
  '16': require('../assets/images/card_16.webp'),
  '17': require('../assets/images/card_17.webp'),
  '18': require('../assets/images/card_18.webp'),
  '19': require('../assets/images/card_19.webp'),
  '20': require('../assets/images/card_20.webp'),
  '21': require('../assets/images/card_21.webp'),
  '22': require('../assets/images/card_22.webp'),
  '23': require('../assets/images/card_23.webp'),
  '24': require('../assets/images/card_24.webp'),
  '25': require('../assets/images/card_25.webp'),
  '26': require('../assets/images/card_26.webp'),
  '27': require('../assets/images/card_27.webp'),
  '28': require('../assets/images/card_28.webp'),
  '29': require('../assets/images/card_29.webp'),
  '30': require('../assets/images/card_30.webp'),
  '31': require('../assets/images/card_31.webp'),
  '32': require('../assets/images/card_32.webp'),
  '33': require('../assets/images/card_33.webp'),
  '34': require('../assets/images/card_34.webp'),
  '35': require('../assets/images/card_35.webp'),
  '36': require('../assets/images/card_36.webp'),
  '37': require('../assets/images/card_37.webp'),
  '38': require('../assets/images/card_38.webp'),
  '39': require('../assets/images/card_39.webp'),
  '40': require('../assets/images/card_40.webp'),
};

export default cardImages;
